ci: Do not install Podman
The Ubuntu runner images already offer Podman by default, so we don't
need to install it. Moreover, by installing Podman, we encounter the
following error:

  Error: failed to open 2048 locks in /libpod_lock: numerical result out of range

Fixes #7